name: sparse_minimum_distortion
dependencies:
  - python=3.7
  - numpy
  - scipy
  - ipyparallel
  - pandas
  - matplotlib
  - pip
  - seaborn
  - pip:
    - mir_eval
    - repsimtools
    - pyroomacoustics
